#!/bin/sh

# nginx
site=tiny-ssdp
if [ -f "/etc/nginx/sites-enabled/$site" ]
then
	nginx=true
fi

if [ -f "/etc/apache2/sites-available/$site.conf" ]
then
	apache2=true
fi

rm -f "/etc/nginx/sites-available/$site"
rm -f "/etc/nginx/sites-enabled/$site"

rm -f "/etc/apache2/sites-available/$site"
rm -f "/etc/apache2/sites-enabled/$site"

if which systemd > /dev/null
then
	# remove systemd
	systemctl is-active --quiet tiny-ssdp.service && systemctl disable tiny-ssdp.service
	rm -f "/etc/systemd/system/tiny-ssdp.service"

	[ ! -z "$nginx" ] && systemctl reload nginx
	[ ! -z "$apache2" ] && systemctl restart apache2
else
	# remove SystemV-init
	update-rc.d -f tiny-ssdp remove || :
	rm -f "/etc/init.d/tiny-ssdp"

	[ ! -z "$nginx" ] && invoke-rc.d nginx reload
	[ ! -z "$apache2" ] && invoke-rc.d apache2 restart
fi

exit 0

