#!/bin/sh

set -e

site=tiny-ssdp.conf
daemon=tiny-ssdp
apache=/etc/init.d/apache2

if [ -e "/etc/apache2/sites-available/$site" -a -d "/etc/apache2/sites-enabled/" ]
then 
	cd "/etc/apache2/sites-enabled/"
	[ -e "$site" ] || ln -sf "../sites-available/$site" .
fi

if [ -e "$apache" ]
then
	"$apache" restart || :
fi

update-rc.d -f "$daemon" defaults

