#!/bin/sh

set -e

# apache
site=tiny-ssdp.conf
if [ -d "/etc/apache2/sites-available/" -a -d "/etc/apache2/sites-enabled/" ]
then 
	cp "/usr/lib/tiny-ssdp/apache2/$site" "/etc/apache2/sites-available/"
	cd "/etc/apache2/sites-enabled/"
	ln -sf "../sites-available/$site" .
fi
invoke-rc.d apache2 restart

if which systemd > /dev/null
then
	# configure and enable systemd
	cp -f "/usr/lib/tiny-ssdp/startup/tiny-ssdp.service" /etc/systemd/system/
	systemctl enable tiny-ssdp.service
	systemctl start tiny-ssdp.service
else
	# configure and enable systemV-init
	cp -f "/usr/lib/tiny-ssdp/startup/tiny-ssdp" /etc/init.d/
	update-rc.d -f tiny-ssdp defaults
	service tiny-ssdp start
fi

