#!/bin/sh

set -e

# apache2
rm -f "/etc/apache2/sites-enabled/tiny-ssdp.conf" || :
rm -f "/etc/apache2/sites-available/tiny-ssdp.conf" || :
invoke-rc.d apache2 restart || :

if which systemd > /dev/null
then
	# remove sytemd
	systemctl disable tiny-ssdp.service
	rm -f "/etc/systemd/system/tiny-ssdp.service" || :
else
	# remove systemV-init
	update-rc.d -f tiny-ssdp remove
	rm -f "/etc/init.d/tiny-ssdp" || :
fi

