#!/bin/sh

if which systemd > /dev/null
then
	# stop systemd
	systemctl is-active --quiet tiny-ssdp.service && systemctl stop tiny-ssdp.service
else
	# stop systemV-init
	service tiny-ssdp stop || :
fi

exit 0

